INSERT into obchod (nazov_obchodu) values ('KampfLand');
INSERT into obchod (nazov_obchodu) values ('Tesco');
INSERT into obchod (nazov_obchodu) values ('Billa');
INSERT into prevadzka (adresa,otv_hodiny,zatv_hodiny,obchod_id) values ('Konevova 1', '10:30', '16:30',1);
INSERT into prevadzka (adresa,otv_hodiny,zatv_hodiny,obchod_id) values ('Tulska 3', '10:30', '18:30',2);
INSERT into prevadzka (adresa,otv_hodiny,zatv_hodiny,obchod_id) values ('Mrdka 2', '10:30', '16:30',3);
INSERT into prevadzka (adresa,otv_hodiny,zatv_hodiny,obchod_id) values ('Kys 14', '10:00', '16:30',1);
INSERT into tovar (nazov, category, prev_id, mnozstvo) values ('Jameson', 'ALKOHOL', 4, 5);
INSERT into tovar (nazov, category, prev_id, mnozstvo) values ('Rozek', 'PECIVO', 1, 3);
INSERT into tovar (nazov, category, prev_id, mnozstvo) values ('Mila', 'SLADKE', 2, 4);
INSERT into tovar (nazov, category, prev_id, mnozstvo) values ('Slovakia', 'SLANE', 3, 4);
INSERT into tovar (nazov, category, prev_id, mnozstvo) values ('Kofola', 'NEALKO', 4, 5);
INSERT into tovar (nazov, category, prev_id, mnozstvo) values ('Lina', 'SLADKE', 2, 6);
INSERT into tovar (nazov, category, prev_id, mnozstvo) values ('DRU', 'SLANE', 4, 7);
INSERT into tovar (nazov, category, prev_id, mnozstvo) values ('DRU', 'SLANE', 3, 7);
